manifest_version = "3"

[package]
name = "demos.heap_features"
version = "0.1.0"

[module]
name = "demos.heap_features"
path = "heap_features.prime"
visibility = "pub"

[libraries]
core_types = { name = "core.types", path = "../../core/types.prime", visibility = "pub" }
