manifest_version = "3"

[package]
name = "demos.interface_generics"
version = "0.1.0"

[module]
name = "demos.interface_generics"
path = "interface_generics_demo.prime"
visibility = "pub"

[libraries]
core_types = { name = "core.types", path = "../../core/types.prime", visibility = "pub" }
