manifest_version = "2"

[package]
entry = "app::main"
kind = "binary"
name = "prime-lang-playground"
version = "0.1.0"

[[modules]]
name = "app::main"
path = "main.prime"
visibility = "pub"

[[modules]]
name = "core::types"
path = "types.prime"
visibility = "pub"

[[modules]]
name = "pkg::app"
path = "pkg_app.prime"
visibility = "pub"

[[modules]]
name = "pkg::lib"
path = "pkg_lib.prime"
visibility = "pub"

[[modules]]
name = "demos::generic"
path = "generic_demo.prime"
visibility = "pub"

[[modules]]
name = "demos::heap"
path = "heap_demo.prime"
visibility = "pub"

[[modules]]
name = "demos::heap_features"
path = "heap_features.prime"
visibility = "pub"

[[modules]]
name = "demos::interface_demo"
path = "interface_demo.prime"
visibility = "pub"

[[modules]]
name = "demos::interface_generics"
path = "interface_generics_demo.prime"
visibility = "pub"

[[modules]]
name = "demos::ns"
path = "ns_demo.prime"
visibility = "pub"
