manifest_version = "3"

[workspace]
members = [
  "workspace/app",
  "workspace/core",
  "workspace/pkg/app",
  "workspace/pkg/lib",
  "workspace/demos/generic",
  "workspace/demos/heap",
  "workspace/demos/heap_features",
  "workspace/demos/interface_demo",
  "workspace/demos/interface_generics",
  "workspace/demos/error_handling",
  "workspace/demos/ns",
  "workspace/demos/borrow",
  "workspace/demos/borrow_checker_errors",
  "workspace/demos/patterns",
  "workspace/demos/macro",
  "workspace/demos/lab_demo",
  "workspace/demos/channel_demo",
  "workspace/demos/parallel_demo",
  "workspace/demos/input",
  "workspace/demos/pointer_demo",
  "workspace/demos/closures",
  "workspace/demos/drop_demo",
  "workspace/demos/bare_metal_embedded",
  "workspace/tests/build_input_demo",
  "workspace/tests/basic",
  "workspace/tests/types_numeric",
  "workspace/tests/input_read",
  "workspace/tests/macros",
  "workspace/tests/drop",
  "workspace/libpkg_a",
]
