manifest_version = "3"

[package]
name = "demos::patterns"
version = "0.1.0"

[module]
name = "demos::patterns"
path = "pattern_demo.prime"
visibility = "pub"

[libraries]
core_types = { name = "core::types", path = "../../core/types.prime", visibility = "pub" }
