manifest_version = "3"

[package]
name = "demos::async_demo"
version = "0.1.0"

[module]
name = "demos::async_demo"
path = "async_demo.prime"
visibility = "pub"

[libraries]
core_types = { name = "core::types", path = "../../core/types.prime", visibility = "pub" }
channel_sleep = { name = "demos::async_demo::channel_sleep", path = "./channel_sleep.prime", visibility = "pub"}
